//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForibaBuluteDefterTestProject.ServiceRef {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cloud.eledger.fit.com/ledger")]
    public partial class FaultMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("messages");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cloud.eledger.fit.com/ledger")]
    public partial class SaveResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long ledgerIdField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long ledgerId {
            get {
                return this.ledgerIdField;
            }
            set {
                this.ledgerIdField = value;
                this.RaisePropertyChanged("ledgerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cloud.eledger.fit.com/ledger")]
    public partial class LedgerStream : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private byte[] binaryDataField;
        
        private string hashField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] binaryData {
            get {
                return this.binaryDataField;
            }
            set {
                this.binaryDataField = value;
                this.RaisePropertyChanged("binaryData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
                this.RaisePropertyChanged("hash");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cloud.eledger.fit.com/ledger")]
    public partial class Company : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identifierField;
        
        private int branchIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int branchId {
            get {
                return this.branchIdField;
            }
            set {
                this.branchIdField = value;
                this.RaisePropertyChanged("branchId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cloud.eledger.fit.com/ledger")]
    public partial class SaveRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Company companyField;
        
        private LedgerStream sourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Company company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LedgerStream source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.cloud.eledger.fit.com/ledger", ConfigurationName="ServiceRef.ELedgerCloudService")]
    public interface ELedgerCloudService {
        
        // CODEGEN: Generating message contract since the operation save is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ForibaBuluteDefterTestProject.ServiceRef.FaultMessage), Action="", Name="ServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ForibaBuluteDefterTestProject.ServiceRef.saveResponse1 save(ForibaBuluteDefterTestProject.ServiceRef.saveRequest1 request);
        
        // CODEGEN: Generating message contract since the operation status is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ForibaBuluteDefterTestProject.ServiceRef.FaultMessage), Action="", Name="ServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ForibaBuluteDefterTestProject.ServiceRef.statusResponse1 status(ForibaBuluteDefterTestProject.ServiceRef.statusRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cloud.eledger.fit.com/ledger", Order=0)]
        public ForibaBuluteDefterTestProject.ServiceRef.SaveRequest SaveRequest;
        
        public saveRequest1() {
        }
        
        public saveRequest1(ForibaBuluteDefterTestProject.ServiceRef.SaveRequest SaveRequest) {
            this.SaveRequest = SaveRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cloud.eledger.fit.com/ledger", Order=0)]
        public ForibaBuluteDefterTestProject.ServiceRef.SaveResponse SaveResponse;
        
        public saveResponse1() {
        }
        
        public saveResponse1(ForibaBuluteDefterTestProject.ServiceRef.SaveResponse SaveResponse) {
            this.SaveResponse = SaveResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cloud.eledger.fit.com/ledger")]
    public partial class StatusRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Company companyField;
        
        private long ledgerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Company company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long ledgerId {
            get {
                return this.ledgerIdField;
            }
            set {
                this.ledgerIdField = value;
                this.RaisePropertyChanged("ledgerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cloud.eledger.fit.com/ledger")]
    public partial class StatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class statusRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cloud.eledger.fit.com/ledger", Order=0)]
        public ForibaBuluteDefterTestProject.ServiceRef.StatusRequest StatusRequest;
        
        public statusRequest1() {
        }
        
        public statusRequest1(ForibaBuluteDefterTestProject.ServiceRef.StatusRequest StatusRequest) {
            this.StatusRequest = StatusRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class statusResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cloud.eledger.fit.com/ledger", Order=0)]
        public ForibaBuluteDefterTestProject.ServiceRef.StatusResponse StatusResponse;
        
        public statusResponse1() {
        }
        
        public statusResponse1(ForibaBuluteDefterTestProject.ServiceRef.StatusResponse StatusResponse) {
            this.StatusResponse = StatusResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ELedgerCloudServiceChannel : ForibaBuluteDefterTestProject.ServiceRef.ELedgerCloudService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ELedgerCloudServiceClient : System.ServiceModel.ClientBase<ForibaBuluteDefterTestProject.ServiceRef.ELedgerCloudService>, ForibaBuluteDefterTestProject.ServiceRef.ELedgerCloudService {
        
        public ELedgerCloudServiceClient() {
        }
        
        public ELedgerCloudServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ELedgerCloudServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ELedgerCloudServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ELedgerCloudServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ForibaBuluteDefterTestProject.ServiceRef.saveResponse1 ForibaBuluteDefterTestProject.ServiceRef.ELedgerCloudService.save(ForibaBuluteDefterTestProject.ServiceRef.saveRequest1 request) {
            return base.Channel.save(request);
        }
        
        public ForibaBuluteDefterTestProject.ServiceRef.SaveResponse save(ForibaBuluteDefterTestProject.ServiceRef.SaveRequest SaveRequest) {
            ForibaBuluteDefterTestProject.ServiceRef.saveRequest1 inValue = new ForibaBuluteDefterTestProject.ServiceRef.saveRequest1();
            inValue.SaveRequest = SaveRequest;
            ForibaBuluteDefterTestProject.ServiceRef.saveResponse1 retVal = ((ForibaBuluteDefterTestProject.ServiceRef.ELedgerCloudService)(this)).save(inValue);
            return retVal.SaveResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ForibaBuluteDefterTestProject.ServiceRef.statusResponse1 ForibaBuluteDefterTestProject.ServiceRef.ELedgerCloudService.status(ForibaBuluteDefterTestProject.ServiceRef.statusRequest1 request) {
            return base.Channel.status(request);
        }
        
        public ForibaBuluteDefterTestProject.ServiceRef.StatusResponse status(ForibaBuluteDefterTestProject.ServiceRef.StatusRequest StatusRequest) {
            ForibaBuluteDefterTestProject.ServiceRef.statusRequest1 inValue = new ForibaBuluteDefterTestProject.ServiceRef.statusRequest1();
            inValue.StatusRequest = StatusRequest;
            ForibaBuluteDefterTestProject.ServiceRef.statusResponse1 retVal = ((ForibaBuluteDefterTestProject.ServiceRef.ELedgerCloudService)(this)).status(inValue);
            return retVal.StatusResponse;
        }
    }
}
